name: Keep Supabase Active

on:
  schedule:
    # Run daily at 9:00 AM JST (00:00 UTC)
    - cron: '0 0 * * *'
  workflow_dispatch: # Allow manual triggering

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Supabase client
        run: npm install @supabase/supabase-js

      - name: Run Supabase keep-alive
        env:
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
        run: node scripts/keep-supabase-active.js

      - name: Log completion
        run: |
          echo "✅ Supabase keep-alive completed at $(date)"
          echo "🔗 Repository: ${{ github.repository }}"
          echo "📝 Commit: ${{ github.sha }}"